const DORMITORY_NUMBER_KEY = 'DORMITORY_NUMBER';
const PASSWORD_KEY = 'PASSWORD';
const ACCESS_SESSION_KEY = 'ACCESS_SESSION';

const PERIOD_KEY = 'PERIOD';
const REASONTYPE_KEY = 'REASONTYPE';
const REASONDETAIL_KEY = 'REASONDETAIL';
const DESTINATIONSTATE_KEY = 'DESTINATIONSTATE';
const DESTINATIONCITY_KEY = 'DESTINATIONCITY';
