// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArPkqJI5GKj6_urIz4fms0DLJbZn5LhkI',
    appId: '1:980169749869:web:2bbb550dc4239141fed664',
    messagingSenderId: '980169749869',
    projectId: 'cbhs-d1326',
    authDomain: 'cbhs-d1326.firebaseapp.com',
    storageBucket: 'cbhs-d1326.appspot.com',
    measurementId: 'G-K2GKSSNZ2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbTJBt9AOrZrXX9ziOAj_nSLplvvzyRmY',
    appId: '1:980169749869:android:ab040cf4364d01b7fed664',
    messagingSenderId: '980169749869',
    projectId: 'cbhs-d1326',
    storageBucket: 'cbhs-d1326.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaBGWZX10XALDBGrmfqCz_feMbnMk9b-8',
    appId: '1:980169749869:ios:d21a3e4767802883fed664',
    messagingSenderId: '980169749869',
    projectId: 'cbhs-d1326',
    storageBucket: 'cbhs-d1326.appspot.com',
    iosBundleId: 'test.flutter.cbhs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaBGWZX10XALDBGrmfqCz_feMbnMk9b-8',
    appId: '1:980169749869:ios:d21a3e4767802883fed664',
    messagingSenderId: '980169749869',
    projectId: 'cbhs-d1326',
    storageBucket: 'cbhs-d1326.appspot.com',
    iosBundleId: 'test.flutter.cbhs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArPkqJI5GKj6_urIz4fms0DLJbZn5LhkI',
    appId: '1:980169749869:web:018b3b23bc8e02a5fed664',
    messagingSenderId: '980169749869',
    projectId: 'cbhs-d1326',
    authDomain: 'cbhs-d1326.firebaseapp.com',
    storageBucket: 'cbhs-d1326.appspot.com',
    measurementId: 'G-YZGWFNYTCK',
  );
}
